### ISSUE TITLE
Add triage for PRs

### ISSUE THREAD

**Issue by dogmatic69** [dogmatic69/actions#12]
Taken from [here](https://github.com/actions/labeler)
```
  triage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v2
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
```
